#!/usr/bin/env bash
set -e
root=$(cd $(dirname $0);pwd)
source $root/lib/utils.sh

requires git

initials=${1-brde}
echo "initials $initials"

#### install vim config
[ -e ~/.vim_brde ] || git clone https://github.com/briandemant/vim.git ~/.vim_brde
~/.vim_brde/bootstrap.sh $initials
cd ~/.vim_brde
./install_plugins
cd $root

#### install bash config
ln -s $root/config/bashrc ~/.bashrc_$initials

### install ssh keys
[[ ! -d ~/.ssh ]] && mkdir ~/.ssh && chmod 0600 ~/.ssh
touch ~/.ssh/authorized_keys && chmod 0644 ~/.ssh/authorized_keys
for key in $(ls keys/*.pub); do
	grep "$(head -n1 $key)" ~/.ssh/authorized_keys && echo "$key was installed"
	grep "$(head -n1 $key)" ~/.ssh/authorized_keys || cat $key >> ~/.ssh/authorized_keys && echo "$key installed"	
done

### install LC_WHOAMI
if [[ "$(grep LC_WHOAMI ~/.bashrc)" == "" ]]; then
 cat config/lc_whoami >> ~/.bashrc
fi

