#!/usr/bin/env bash
set -e
root=$(cd $(dirname $0);pwd)
source $root/lib/utils.sh
source ./config/colors

requires git

initials=${1-brde}
echo -e "${GREEN}initials ${RED}$initials${RESET}"

#### install vim config
if [ -e ~/.vim_$initials ]; then
	cd ~/.vim_$initials
	git pull
else
	git clone https://github.com/briandemant/vim.git ~/.vim_$initials
fi
~/.vim_$initials/bootstrap.sh $initials
cd ~/.vim_$initials

echo -e "${GREEN}install vim config${RESET}"
./install_plugins
cd $root

#### install bash config
ln -s $root/config/bashrc ~/.bashrc_$initials

### install ssh keys
[[ ! -d ~/.ssh ]] && mkdir ~/.ssh && chmod 0600 ~/.ssh
touch ~/.ssh/authorized_keys && chmod 0644 ~/.ssh/authorized_keys
for key in $(ls keys/*.pub); do
	grep "$(head -n1 $key)" ~/.ssh/authorized_keys && echo -e "${YELLOW}$key was already installed${RESET}"
	grep "$(head -n1 $key)" ~/.ssh/authorized_keys || cat $key >> ~/.ssh/authorized_keys && echo -e "${GREEN}$key was installed${RESET}"	
done

### install LC_WHOAMI
if [[ "$(grep LC_WHOAMI ~/.bashrc)" == "" ]]; then
 cat config/lc_whoami >> ~/.bashrc
fi

