#!/usr/bin/env bash 
[[ -e /usr/local/etc/bash_completion ]] && source /usr/local/etc/bash_completion
[[ -e /usr/share/doc/cdargs/examples/cdargs-bash.sh ]] && source /usr/share/doc/cdargs/examples/cdargs-bash.sh

alias ls="ls -FG"
alias ll="ls -l"
alias la="ls -lA"
alias lh="ls -lh"

alias grep="egrep --color"

alias mx="chmod +x"
alias tree="tree -l -C -x --dirsfirst"
alias git="HOME=~/.brde/config/ git"

export LC_CTYPE="da_DK.UTF-8"
export LC_WHOAMI=brde
export EDITOR=vim

source ~/.brde/config/colors

[[ -e ~/.brde/local/bashrc ]] && source ~/.brde/local/bashrc

if [ "$TERM" != 'dumb'  ] && [ -n "$BASH" ]; then
	parse_git_branch() {
		git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
	}

	if which git-dirty >/dev/null; then
		git_dirty() {
			git dirty -i
		}
	else
		git_dirty() {
			if [ "$(git status --porcelain 2> /dev/null | head -n1)" != "" ]; then
				echo "*"
			fi
		}
	fi

	export TITLE="\[\033]0;\h: \w\\007\]"

	# server_type=$(hostname -s|egrep -o '^....')
	# if [ "${server_type:0:2}" == "fm" ]; then
	# 	UC=$GREEN
	# 	if [ "${server_type:0:4}" == "fmas" ]; then
	# 		HC=$CYAN
	# 	else
	# 		HC=$RED
	# 	fi
	# fi

	if [ "$(whoami)" == "root" ]; then
		PS_DC=$PS_RC
	else
		PS_DC=$PS_UC
	fi

	PS1="$HC\\h $DC\\w $PS_GREY\$(parse_git_branch)$PS_YELLOW\$(git_dirty)$PS_GREY$PS_RESET\n> "

	export PROMPT_COMMAND='history -a;history -r'

	# write history allways
	shopt -s histappend
	export HISTFILE="$HOME/.brde/local/bash_history"
	export HISTSIZE=10000
	export HISTFILESIZE=$HISTSIZE
	export HISTIGNORE="&:[fb]g:ls:[ ]*:exit:history:env:"
fi

export GIT_AUTHOR_NAME="Brian Demant"
export GIT_AUTHOR_EMAIL="brian.demant@gmail.com"
export PATH=~/.brde/bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/local/sbin:$PATH
source ~/.brde/config/std_functions
# source ~/.brde/config/adserving_functions
source ~/.brde/config/completions

program_exists () {
	type "$1" &> /dev/null ;
}


if program_exists go; then
	export GOROOT=`go env GOROOT`
fi

[[ ! -e ~/.brde/local/bash_history ]] && touch ~/.brde/local/bash_history
