#!/bin/bash
RESET="\033[00m"
GREY="\033[01;30m"
RED="\033[01;31m"
GREEN="\033[01;32m"
YELLOW="\033[01;33m"
BLUE="\033[01;34m"
PURPLE="\033[01;35m"
CYAN="\033[01;36m"

# prompt colors
PS_RESET="\\[\\033[00m\\]"
PS_GREY="\\[\\033[01;30m\\]"
PS_RED="\\[\\033[01;31m\\]"
PS_GREEN="\\[\\033[01;32m\\]"
PS_YELLOW="\\[\\033[01;33m\\]"
PS_BLUE="\\[\\033[01;34m\\]"
PS_PURPLE="\\[\\033[01;35m\\]"
PS_CYAN="\\[\\033[01;36m\\]"

HC=$PS_GREY
# color of folder when root
RC=$PS_RED
# color of folder when regular user
UC=$PS_BLUE