#!/usr/bin/env bash
ssh-copy-key() {
	if [ "$2" == "" ]; then
		user='root'
		server=$1
	else
		user=$1
		server=$2
	fi
	ssh $user@$server 'mkdir -p ~/.ssh;chmod 700 ~/.ssh/;grep briandemant ~/.ssh/authorized_keys > /dev/null || cat >> ~/.ssh/authorized_keys;chmod 644 ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
}

# visual studio code
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

install-myenv() {
	if [ "$2" == "" ]; then
		user='web'
		server=$1
	else
		user=$1
		server=$2
	fi
	ssh $user@$server <<INSTALL
if [ ! -e .brde ]; then
git clone http://github.com/briandemant/myenv.git .brde
cd .brde
else 
	cd .brde
	git pull
fi 
./install
INSTALL
}


