#!/usr/bin/env bash
runcron(){ 
	if [ -f /var/www/*/*/$2admin.php ] ; then
		php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2admin.php $(($(date +%s) - 60 * 60))|| echo "ERROR"
	else
		php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2.php $(($(date +%s) - 60 * 60)) || echo "ERROR"
	fi
}

lesslog(){
	local inst
	if [ -f /var/www/*/*/$2admin.php ] ; then
		inst=$2admin.log
	else
		inst=$2.log
	fi

	if [[ "$3" == "" ]] ; then
		less -r /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$inst
	else
		less -r /var/www/*/cron/log/$1/$3/$inst
	fi
}

taillog(){
	local inst
	if [ -f /var/www/*/*/$2admin.php ] ; then
		inst=$2admin.log
	else
		inst=$2.log
	fi
	
	if [[ "$3" == "" ]] ; then
		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$inst
	else
		tail -f -n10000 /var/www/*/cron/log/$1/$3/$inst
	fi
}

_logs() 
{
	local cur prev
	cur=${COMP_WORDS[COMP_CWORD]}
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	case "$prev" in
		lesslog|taillog|runcron)
			COMPREPLY=( $(compgen -W "$(cd /var/www/*/cron/log/;ls -d *|grep '/' | sed 's/ /\\ /g' |cut -f1 -d\/)" -- $cur) )
			return 0
			;;
		*)
			COMPREPLY=( $(compgen -W "$(cd /var/www/*/{defines,config}/;ls  *.php| sed 's/.php//g' )" -- $cur) )
			return 0
			;;
	esac
}

complete -F _logs lesslog
complete -F _logs taillog
complete -F _logs runcron

ssh-copy-key() {
	if [ "$2" == "" ]; then
		user='root'
		server=$1
	else
		user=$1
		server=$2
	fi
	ssh $user@$server 'mkdir -p ~/.ssh;chmod 700 ~/.ssh/;grep briandemant ~/.ssh/authorized_keys > /dev/null || cat >> ~/.ssh/authorized_keys;chmod 644 ~/.ssh/authorized_keys' < ~/.ssh/id_rsa.pub
}

# visual studio code
function code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $*; }

install-myenv() {
	if [ "$2" == "" ]; then
		user='root'
		server=$1
	else
		user=$1
		server=$2
	fi
	ssh $user@$server '[ -e .brde ] && exit; git clone http://github.com/briandemant/myenv.git ~/.brde ; cd .brde ; ./install'
}


