#!/usr/bin/env bash
runcron(){ 
	php /var/www/*/cron/cronRunner.php /var/www/*/cron/.. /var/www/*/cron/jobs/$1.php /var/www/*/*/$2admin.php 1320168191 || echo "ERROR"
}

lesslog(){
	if [[ "$3" == "" ]] ; then
		less /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2*.log
	else
		less /var/www/*/cron/log/$1/$3/$2*.log
	fi
}

taillog(){
	if [[ "$3" == "" ]] ; then
		tail -f -n10000 /var/www/*/cron/log/$1/$(date +%Y-%m-%d)/$2*.log
	else
		tail -f -n10000 /var/www/*/cron/log/$1/$3/$2*.log
	fi
}

_logs() 
{
	local cur prev
	cur=${COMP_WORDS[COMP_CWORD]}
	prev="${COMP_WORDS[COMP_CWORD-1]}"
	echo ">>>$0"
	case "$prev" in
		lesslog|taillog)
			COMPREPLY=( $(compgen -W "$(cd /var/www/*/cron/log/;ls -d *|grep '/' | sed 's/ /\\ /g' |cut -f1 -d\/)" -- $cur) )
			return 0
			;;
		*)
			COMPREPLY=( $(compgen -W "$(cd /var/www/*/cron/log/$prev/;ls -d *|grep '/' | sed 's/ /\\ /g' |cut -f1 -d\/)" -- $cur) )
			return 0
			;;
	esac
}

complete -F _logs lesslog
complete -F _logs taillog
